Ext.define("ExtjsApp.store.Products", {
  extend: "Ext.data.Store",
  alias: "store.products",
  storeId: "ProductsStore",

  model: "ExtjsApp.model.Product",

  pageSize: 10,

  proxy: {
    type: "memory",
    enablePaging: true,
  },

  autoLoad: true,

  data: [
    {
      id: 1,
      name: "Телефон",
      description: 'Смартфон 5.5"',
      price: 12000.5,
      quantity: 10,
    },
    {
      id: 2,
      name: "Ноутбук",
      description: "Игровой ноутбук",
      price: 55000.0,
      quantity: 0,
    },
    {
      id: 3,
      name: "Клавиатура",
      description: "Механическая клавиатура",
      price: 3500.0,
      quantity: 5,
    },
    {
      id: 4,
      name: "Монитор",
      description: '27" IPS',
      price: 18000.0,
      quantity: 2,
    },
    {
      id: 5,
      name: "Мышь",
      description: "Беспроводная мышь",
      price: 900.0,
      quantity: 0,
    },
    {
      id: 6,
      name: "Наушники",
      description: "Bluetooth гарнитура",
      price: 2500.0,
      quantity: 15,
    },
    {
      id: 7,
      name: "Принтер",
      description: "Лазерный принтер",
      price: 12000.0,
      quantity: 3,
    },
    {
      id: 8,
      name: "Флешка",
      description: "USB 64GB",
      price: 600.0,
      quantity: 20,
    },
    { id: 9, name: "SSD", description: "NVMe 1TB", price: 8000.0, quantity: 7 },
    {
      id: 10,
      name: "Видеокарта",
      description: "RTX 4060 8GB",
      price: 38000.0,
      quantity: 5,
    },
    {
      id: 11,
      name: "Оперативная память",
      description: "DDR4 16GB",
      price: 4500.0,
      quantity: 12,
    },
    {
      id: 12,
      name: "Колонки",
      description: "2.1 акустика",
      price: 3200.0,
      quantity: 6,
    },
    {
      id: 13,
      name: "Веб-камера",
      description: "FullHD 1080p",
      price: 2100.0,
      quantity: 9,
    },
    {
      id: 14,
      name: "Микрофон",
      description: "Студийный USB",
      price: 5000.0,
      quantity: 4,
    },
    {
      id: 15,
      name: "Игровое кресло",
      description: "Эргономичное кресло",
      price: 15000.0,
      quantity: 2,
    },
    {
      id: 16,
      name: "Телевизор",
      description: 'SmartTV 43"',
      price: 32000.0,
      quantity: 5,
    },
    {
      id: 17,
      name: "Планшет",
      description: '10" Android',
      price: 22000.0,
      quantity: 8,
    },
    {
      id: 18,
      name: "Часы",
      description: "Умные часы",
      price: 11000.0,
      quantity: 6,
    },
    {
      id: 19,
      name: "Блок питания",
      description: "750W Gold",
      price: 6500.0,
      quantity: 10,
    },
    {
      id: 20,
      name: "Материнская плата",
      description: "ATX Z690",
      price: 14000.0,
      quantity: 3,
    },
    {
      id: 21,
      name: "Игровая приставка",
      description: "PlayStation 5",
      price: 65000.0,
      quantity: 1,
    },
    {
      id: 22,
      name: "Контроллер",
      description: "Геймпад Xbox",
      price: 5500.0,
      quantity: 14,
    },
    {
      id: 23,
      name: "Роутер",
      description: "Wi-Fi 6",
      price: 8000.0,
      quantity: 7,
    },
    {
      id: 24,
      name: "Внешний HDD",
      description: "2TB USB 3.0",
      price: 6000.0,
      quantity: 9,
    },
    {
      id: 25,
      name: "Кулер",
      description: "Охлаждение CPU",
      price: 3500.0,
      quantity: 11,
    },
    {
      id: 26,
      name: "Коврик для мыши",
      description: "Игровой XXL",
      price: 1200.0,
      quantity: 18,
    },
    {
      id: 27,
      name: "Сканер",
      description: "Документ-сканер",
      price: 10000.0,
      quantity: 2,
    },
    {
      id: 28,
      name: "Проектор",
      description: "FullHD проектор",
      price: 27000.0,
      quantity: 3,
    },
    {
      id: 29,
      name: "Камера",
      description: "Зеркальная камера",
      price: 75000.0,
      quantity: 2,
    },
    {
      id: 30,
      name: "Шлем VR",
      description: "Очки виртуальной реальности",
      price: 35000.0,
      quantity: 4,
    },
  ],
});
